@echo off
echo Starting the High-Performance Matching Engine Server...
echo Leave this window open! It is waiting for connections...

docker run -it --rm -p 9000:9000 orderbook-engine ./build/matching_engine --port 9000
